# Generated by Django 6.0.2 on 2026-03-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='otp',
            new_name='generated_otp',
        ),
    ]
